# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

# Application Properties
properties:
  apisecret: secret
  public-paths:
    - "/actuator/**"
    - "/v3/api-docs/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/public/**"
    - "/wua"
    - "/accounts/v1"
  challenge-response-endpoint: "/public/auth/session/response"
  walletprovider:
    baseurl: http://
    wua-path: /wallet-provider/wallet-unit-attestation
  attributeattestation:
    baseurl: http://
    paths:
      post: /attestation
      get-by-id: /attestation
      get-by-key: attestation/user
  walletaccount:
    baseurl: http://
    paths:
      post: /account
      get: /account
  challenge-cache:
    ttl-seconds: 30

# Wallet Client Gateway Configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 10m
spring:
  application:
    name: wallet-client-gateway

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
