# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

# Application Properties
properties:
  apisecret: secret
  public-paths:
    - "/actuator/**"
    - "/v3/api-docs/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/public/**"
    - "/wua"
    - "/accounts/v1"
  walletprovider:
    baseurl: http://
    wua-path: /wallet-provider/wallet-unit-attestation
  attributeattestation:
    baseurl: http://
    paths:
      post: /attestation
      get-by-id: /attestation
      get-by-key: attestation/user
  walletaccount:
    baseurl: http://
    paths:
      post: /account
      get: /account
  challenge-cache:
    ttl-seconds: 30
  authorization-server:
    baseurl: http://localhost:8089
    private-jwt-audience:
  oidc-claims:
    personal-identity-number: https://id.oidc.se/claim/personalIdentityNumber

# Wallet Client Gateway Configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 10m
spring:
  application:
    name: wallet-client-gateway
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          myprovider:
            client-id: http://localhost:8080/
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          myprovider:
            authorization-uri: "${properties.authorization-server.baseurl}/realms/wallet/protocol/openid-connect/auth"
            jwk-set-uri: "${properties.authorization-server.baseurl}/realms/wallet/protocol/openid-connect/certs"
            token-uri: "${properties.authorization-server.baseurl}/realms/wallet/protocol/openid-connect/token"
            user-info-endpoint-uri: "${properties.authorization-server.baseurl}/realms/wallet/protocol/openid-connect/userinfo"

credential:
  bundles:
    keystore:
      private-jwt-keys:
        location: classpath:keystore-wallet-app-bff-local.p12
        password: changeit
        type: PKCS12
    jks:
      myprovider:
        store-reference: private-jwt-keys
        name: "Private JWT - KeyPair"
        key:
          alias: wallet-app-bff-local
          key-password: changeit

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
