# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

services:
  valkey:
    image: valkey/valkey:9.0.1@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    ports:
      - "6379:6379"
    networks:
      - wallet-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4-0@sha256:2b32a51a31e8d780d9fa9a69a59ead69975263c61b5dd13559090e22aa26f100
    container_name: wcg-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - wallet-network
    ports:
      - "8089:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keystore-wallet-app-bff-local.p12:/opt/keycloak/conf/client-keystore.p12

networks:
  wallet-network:
    driver: bridge
